## Sample generation
#### load trained model -> generate samples

In [32]:
import numpy as np
from tensorflow import keras

input_path = 'D:\\Studia\\SEM6\\biai\\projekt\\pretrained_models\\'
input_file_name = 'beth_transp_1024_20epochs_143.0m.h5'

model = keras.models.load_model(input_path + input_file_name)

### Generate seed

In [69]:
import numpy as np

INPUT_SIZE = 128
# [batch_size, sequence_len, input_dim]
# generate random seed
seed = np.random.random((1, 1, INPUT_SIZE)) * 0.5
# seed = np.zeros((1, 1, INPUT_SIZE))
# seed[:,:,60:80] = np.random.randint(0, 2, size=20)

### Generate sequence

In [70]:
# at default 1 frame = 0.025s
SEQUENCE_LENGTH = 100

x = seed
for i in range(SEQUENCE_LENGTH):
    print(i, end=',')
    res = model.predict(x, batch_size=1)
    x = np.concatenate([seed, res], axis=1)
    
res.shape

(1, 1, 128),(1, 2, 128),(1, 3, 128),(1, 4, 128),(1, 5, 128),(1, 6, 128),(1, 7, 128),(1, 8, 128),(1, 9, 128),(1, 10, 128),(1, 11, 128),(1, 12, 128),(1, 13, 128),(1, 14, 128),(1, 15, 128),(1, 16, 128),(1, 17, 128),(1, 18, 128),(1, 19, 128),(1, 20, 128),(1, 21, 128),(1, 22, 128),(1, 23, 128),(1, 24, 128),(1, 25, 128),(1, 26, 128),(1, 27, 128),(1, 28, 128),(1, 29, 128),(1, 30, 128),(1, 31, 128),(1, 32, 128),(1, 33, 128),(1, 34, 128),(1, 35, 128),(1, 36, 128),(1, 37, 128),(1, 38, 128),(1, 39, 128),(1, 40, 128),(1, 41, 128),(1, 42, 128),(1, 43, 128),(1, 44, 128),(1, 45, 128),(1, 46, 128),(1, 47, 128),(1, 48, 128),(1, 49, 128),(1, 50, 128),(1, 51, 128),(1, 52, 128),(1, 53, 128),(1, 54, 128),(1, 55, 128),(1, 56, 128),(1, 57, 128),(1, 58, 128),(1, 59, 128),(1, 60, 128),(1, 61, 128),(1, 62, 128),(1, 63, 128),(1, 64, 128),(1, 65, 128),(1, 66, 128),(1, 67, 128),(1, 68, 128),(1, 69, 128),(1, 70, 128),(1, 71, 128),(1, 72, 128),(1, 73, 128),(1, 74, 128),(1, 75, 128),(1, 76, 128),(1, 77, 128),(1, 78, 

(1, 100, 128)

### Save to midi format

In [71]:
res = res.round()
res = np.squeeze(res, axis=0)
res[0] = np.zeros(INPUT_SIZE)
res = np.append(res, np.zeros((1, INPUT_SIZE)), axis=0)

In [72]:
print(res)
print(res[100])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


In [73]:
# from midi_numpy.common import save_numpy_midi
from midi_numpy.numpy_to_midi import pipe_reverse as numpy2midi
from datetime import datetime

tim = str(datetime.now()).replace(' ', '_').replace(':', '_')
output_path = 'D:\\Studia\\SEM6\\biai\\projekt\\pretrained_models\\'
output_file_name = f'sample_{SEQUENCE_LENGTH}_{tim}.mid'

# save_numpy_midi(, np.squeeze(res, axis=0))
# res = np.append(res, np.zeros((1, INPUT_SIZE)))
# if len(res.shape) == 3:
#     res = np.squeeze(res, axis=0)

print(res.shape)
mid = numpy2midi(res)
for n in mid.tracks[0]:
    print(n)
mid.save(output_path + output_file_name)

(101, 128)
note_on channel=0 note=36 velocity=127 time=25
note_on channel=0 note=44 velocity=127 time=0
note_on channel=0 note=48 velocity=127 time=0
note_on channel=0 note=44 velocity=0 time=50
note_on channel=0 note=48 velocity=0 time=100
note_on channel=0 note=36 velocity=0 time=250
